"""Essential SSDT generators"""

class EssentialGenerators:
    """Generate essential SSDTs"""
    
    @staticmethod
    def generate_ec(output_path, dsdt_context=None):
        """Generate SSDT-EC"""
        # Get LPC bridge path
        if dsdt_context and dsdt_context.lpc_bridge:
            lpc_path = dsdt_context.lpc_bridge
            path_comment = f" * Device Path: {lpc_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            lpc_path = "_SB.PCI0.LPCB"
            path_comment = f" * Device Path: {lpc_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format for External and Scope
        external_path = lpc_path.replace('.', '_.') + '_'
        scope_path = lpc_path.replace('_', '')
        
        content = f"""/*
 * SSDT-EC - Fake Embedded Controller
 * Required for Catalina+ to boot
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "EC", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Device (EC)
        {{
            Name (_HID, "ACID0001")
            Method (_STA, 0, NotSerialized)
            {{
                If (_OSI ("Darwin"))
                {{
                    Return (0x0F)
                }}
                Else
                {{
                    Return (Zero)
                }}
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
    
    @staticmethod
    def generate_plug(output_path, dsdt_context=None):
        """Generate SSDT-PLUG"""
        # Get CPU path
        if dsdt_context and dsdt_context.cpu_path:
            cpu_path = dsdt_context.cpu_path
            path_comment = f" * CPU Path: {cpu_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            cpu_path = "_PR.CPU0"
            path_comment = f" * CPU Path: {cpu_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        content = f"""/*
 * SSDT-PLUG - CPU Power Management
 * Enables XCPM on Haswell and newer
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "PLUG", 0x00000000)
{{
    External ({cpu_path}, ProcessorObj)
    
    Scope ({cpu_path})
    {{
        If (_OSI ("Darwin"))
        {{
            Method (_DSM, 4, NotSerialized)
            {{
                If (!Arg2)
                {{
                    Return (Buffer (One) {{ 0x03 }})
                }}
                
                Return (Package (0x02)
                {{
                    "plugin-type", 
                    One
                }})
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
    
    @staticmethod
    def generate_awac(output_path, dsdt_context=None):
        """Generate SSDT-AWAC"""
        # AWAC patch is generic, but we can note if system was analyzed
        if dsdt_context and dsdt_context.analyzed:
            status_comment = " * Status: Generic patch (no device-specific paths needed)"
        else:
            status_comment = " * Status: Generic patch"
        
        content = f"""/*
 * SSDT-AWAC - System Clock Fix
 * Forces RTC to be enabled on 300+ series
 * Generated by Acpi Analyzer v1.0
 *
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "AWAC", 0x00000000)
{{
    External (STAS, IntObj)
    
    Scope (_SB)
    {{
        Method (_INI, 0, NotSerialized)
        {{
            If (_OSI ("Darwin"))
            {{
                STAS = One
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
