"""Hardware SSDT generators"""

class HardwareGenerators:
    """Generate hardware-related SSDTs"""
    
    @staticmethod
    def generate_hpet(output_path, dsdt_context=None):
        """Generate SSDT-HPET"""
        # Get HPET path
        if dsdt_context and dsdt_context.hpet_device:
            hpet_path = dsdt_context.hpet_device
            path_comment = f" * Device Path: {hpet_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            hpet_path = "_SB.PCI0.LPCB.HPET"
            path_comment = f" * Device Path: {hpet_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format
        external_path = hpet_path.replace('.', '_.') + '_'
        scope_path = hpet_path.replace('_', '')
        
        content = f"""/*
 * SSDT-HPET - IRQ Conflict Resolution
 * Fixes audio and USB issues
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "HPET", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Name (_CRS, ResourceTemplate ()
        {{
            IRQNoFlags () {{0,8,11}}
            Memory32Fixed (ReadWrite,
                0xFED00000,
                0x00000400
            )
        }})
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
    
    @staticmethod
    def generate_pmc(output_path, dsdt_context=None):
        """Generate SSDT-PMC"""
        # Get LPC bridge path
        if dsdt_context and dsdt_context.lpc_bridge:
            lpc_path = dsdt_context.lpc_bridge
            path_comment = f" * Device Path: {lpc_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            lpc_path = "_SB.PCI0.LPCB"
            path_comment = f" * Device Path: {lpc_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format
        external_path = lpc_path.replace('.', '_.') + '_'
        scope_path = lpc_path.replace('_', '')
        
        content = f"""/*
 * SSDT-PMC - NVRAM Support
 * Required for 300+ series chipsets
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "PMC", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Device (PMCR)
        {{
            Name (_HID, EisaId ("APP9876"))
            Name (_CRS, ResourceTemplate ()
            {{
                Memory32Fixed (ReadWrite,
                    0xFE000000,
                    0x00010000
                )
            }})
            Method (_STA, 0, NotSerialized)
            {{
                If (_OSI ("Darwin"))
                {{
                    Return (0x0F)
                }}
                Else
                {{
                    Return (Zero)
                }}
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
    
    @staticmethod
    def generate_sbus(output_path, dsdt_context=None):
        """Generate SSDT-SBUS"""
        # Get SMBus path
        if dsdt_context and dsdt_context.smbus:
            sbus_path = dsdt_context.smbus
            path_comment = f" * Device Path: {sbus_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            sbus_path = "_SB.PCI0.SBUS"
            path_comment = f" * Device Path: {sbus_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format
        external_path = sbus_path.replace('.', '_.') + '_'
        scope_path = sbus_path.replace('_', '')
        
        content = f"""/*
 * SSDT-SBUS - System Management Bus
 * Adds SMBus support
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "SBUS", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Device (BUS0)
        {{
            Name (_CID, "smbus")
            Name (_ADR, Zero)
            Device (DVL0)
            {{
                Name (_ADR, 0x57)
                Name (_CID, "diagsvault")
            }}
            Method (_STA, 0, NotSerialized)
            {{
                If (_OSI ("Darwin"))
                {{
                    Return (0x0F)
                }}
                Else
                {{
                    Return (Zero)
                }}
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
