"""Laptop-specific SSDT generators"""

class LaptopGenerators:
    """Generate laptop-specific SSDTs"""
    
    @staticmethod
    def generate_pnlf(output_path, dsdt_context=None):
        """Generate SSDT-PNLF for backlight control"""
        # Get GPU path
        if dsdt_context and dsdt_context.gpu_device:
            gpu_path = dsdt_context.gpu_device
            path_comment = f" * Device Path: {gpu_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            gpu_path = "_SB.PCI0.GFX0"
            path_comment = f" * Device Path: {gpu_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format
        external_path = gpu_path.replace('.', '_.') + '_'
        scope_path = gpu_path.replace('_', '')
        
        content = f"""/*
 * SSDT-PNLF - Backlight Control
 * Required for laptop backlight functionality
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "PNLF", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Device (PNLF)
        {{
            Name (_HID, EisaId ("APP0002"))
            Name (_CID, "backlight")
            Name (_UID, 0x10)
            Method (_STA, 0, NotSerialized)
            {{
                If (_OSI ("Darwin"))
                {{
                    Return (0x0F)
                }}
                Else
                {{
                    Return (Zero)
                }}
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
    
    @staticmethod
    def generate_als0(output_path, dsdt_context=None):
        """Generate SSDT-ALS0 for ambient light sensor"""
        # Get LPC bridge path
        if dsdt_context and dsdt_context.lpc_bridge:
            lpc_path = dsdt_context.lpc_bridge
            path_comment = f" * Device Path: {lpc_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            lpc_path = "_SB.PCI0.LPCB"
            path_comment = f" * Device Path: {lpc_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format
        external_path = lpc_path.replace('.', '_.') + '_'
        scope_path = lpc_path.replace('_', '')
        
        content = f"""/*
 * SSDT-ALS0 - Ambient Light Sensor
 * Adds fake ALS device
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "ALS0", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Device (ALS0)
        {{
            Name (_HID, "ACPI0008")
            Name (_CID, "smc-als")
            Name (_ALI, 0x012C)
            Name (_ALR, Package (0x01)
            {{
                Package (0x02)
                {{
                    0x64, 
                    0x012C
                }}
            }})
            Method (_STA, 0, NotSerialized)
            {{
                If (_OSI ("Darwin"))
                {{
                    Return (0x0F)
                }}
                Else
                {{
                    Return (Zero)
                }}
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
    
    @staticmethod
    def generate_gpi0(output_path, dsdt_context=None):
        """Generate SSDT-GPI0 for GPIO"""
        # Get GPIO path
        if dsdt_context and dsdt_context.gpio_device:
            gpio_path = dsdt_context.gpio_device
            path_comment = f" * Device Path: {gpio_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            gpio_path = "_SB.PCI0.GPI0"
            path_comment = f" * Device Path: {gpio_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format
        external_path = gpio_path.replace('.', '_.') + '_'
        scope_path = gpio_path.replace('_', '')
        
        content = f"""/*
 * SSDT-GPI0 - GPIO Controller
 * Required for I2C trackpad support
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "GPI0", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Method (_STA, 0, NotSerialized)
        {{
            If (_OSI ("Darwin"))
            {{
                Return (0x0F)
            }}
            Else
            {{
                Return (Zero)
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
