"""USB-related SSDT generators"""

class USBGenerators:
    """Generate USB-related SSDTs"""
    
    @staticmethod
    def generate_usbx(output_path, dsdt_context=None):
        """Generate SSDT-USBX for USB power properties"""
        # Get USB controller path
        if dsdt_context and dsdt_context.usb_controller:
            usb_path = dsdt_context.usb_controller
            path_comment = f" * Device Path: {usb_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            usb_path = "_SB.PCI0.XHC"
            path_comment = f" * Device Path: {usb_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format
        external_path = usb_path.replace('.', '_.') + '_'
        scope_path = usb_path.replace('_', '')
        
        content = f"""/*
 * SSDT-USBX - USB Power Properties
 * Sets proper USB power values
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "USBX", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Device (USBX)
        {{
            Name (_ADR, Zero)
            Method (_DSM, 4, NotSerialized)
            {{
                If (!Arg2)
                {{
                    Return (Buffer (One) {{ 0x03 }})
                }}
                
                Return (Package (0x08)
                {{
                    "kUSBSleepPowerSupply", 
                    0x13EC, 
                    "kUSBSleepPortCurrentLimit", 
                    0x0834, 
                    "kUSBWakePowerSupply", 
                    0x13EC, 
                    "kUSBWakePortCurrentLimit", 
                    0x0834
                }})
            }}
            Method (_STA, 0, NotSerialized)
            {{
                If (_OSI ("Darwin"))
                {{
                    Return (0x0F)
                }}
                Else
                {{
                    Return (Zero)
                }}
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
    
    @staticmethod
    def generate_usb_reset(output_path, dsdt_context=None):
        """Generate SSDT-USB-Reset"""
        # Get USB controller path
        if dsdt_context and dsdt_context.usb_controller:
            usb_path = dsdt_context.usb_controller
            rhub_path = f"{usb_path}.RHUB"
            path_comment = f" * Device Path: {rhub_path} (detected from DSDT)"
            status_comment = " * Status: Compatible with your system"
        else:
            rhub_path = "_SB.PCI0.XHC.RHUB"
            path_comment = f" * Device Path: {rhub_path} (generic - not detected)"
            status_comment = " * WARNING: Please verify this path matches your DSDT"
        
        # Convert path format
        external_path = rhub_path.replace('.', '_.') + '_'
        scope_path = rhub_path.replace('_', '')
        
        content = f"""/*
 * SSDT-USB-Reset - Reset USB Hubs
 * Helps with USB detection issues
 * Generated by Acpi Analyzer v1.0
 *
{path_comment}
{status_comment}
 */
DefinitionBlock ("", "SSDT", 2, "ACPI", "USBRST", 0x00000000)
{{
    External ({external_path}, DeviceObj)
    
    Scope ({scope_path})
    {{
        Method (_STA, 0, NotSerialized)
        {{
            If (_OSI ("Darwin"))
            {{
                Return (Zero)
            }}
            Else
            {{
                Return (0x0F)
            }}
        }}
    }}
}}
"""
        with open(output_path, 'w') as f:
            f.write(content)
        return True
